[package]
name = "ashlang-spartan"
version = "0.1.0"
edition = "2021"

[dependencies]
ashlang = { path = "../ashlang" }
curve25519-dalek = "4.1.3"
merlin = "3.0.0"
rand = "0.8.5"
scalarff = "0.1.1"

[dependencies.spartan]
version = "0.8.0"
default-features = false
